"""remove_cover_pic_from_users

Revision ID: 844c1b720414
Revises: f5bbf72df8e0
Create Date: 2023-03-21 17:10:39.660349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '844c1b720414'
down_revision = 'f5bbf72df8e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('cover_pic')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_pic', sa.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
